name: Idea
description: Suggest a change or a new feature.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What you have in mind
